#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

WHISPER_CPP_REPO_URL="${WHISPER_CPP_REPO_URL:-https://github.com/ggml-org/whisper.cpp.git}"
WHISPER_CPP_REF="${WHISPER_CPP_REF:-master}"
WHISPER_VAD_MODEL="${WHISPER_VAD_MODEL:-silero-v6.2.0}"
WORK_DIR="${WORK_DIR:-${REPO_ROOT}/.build/whisper.cpp}"
BUILD_DIR="${BUILD_DIR:-${WORK_DIR}/build-vscode-macos-arm64}"
OUTPUT_DIR="${1:-${REPO_ROOT}/vendor/whisper}"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This setup script targets macOS Apple Silicon only." >&2
  exit 1
fi

if [[ "$(uname -m)" != "arm64" ]]; then
  echo "This setup script targets arm64, but this machine reports: $(uname -m)" >&2
  exit 1
fi

require_command git
require_command cmake
require_command sysctl

mkdir -p "$(dirname "${WORK_DIR}")"

if [[ ! -d "${WORK_DIR}/.git" ]]; then
  git clone "${WHISPER_CPP_REPO_URL}" "${WORK_DIR}"
fi

git -C "${WORK_DIR}" fetch --tags --prune
git -C "${WORK_DIR}" checkout "${WHISPER_CPP_REF}"

MODELS_STAGING_DIR="${WORK_DIR}/models-vscode"
mkdir -p "${MODELS_STAGING_DIR}"

"${WORK_DIR}/models/download-vad-model.sh" "${WHISPER_VAD_MODEL}" "${MODELS_STAGING_DIR}"

cmake -S "${WORK_DIR}" -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DBUILD_SHARED_LIBS=OFF \
  -DWHISPER_BUILD_TESTS=OFF \
  -DWHISPER_BUILD_EXAMPLES=ON \
  -DWHISPER_BUILD_SERVER=OFF \
  -DGGML_ACCELERATE=ON \
  -DGGML_BLAS=ON \
  -DGGML_BLAS_VENDOR=Apple \
  -DGGML_METAL=ON \
  -DGGML_METAL_EMBED_LIBRARY=ON

cmake --build "${BUILD_DIR}" --config Release --target whisper-cli -j "$(sysctl -n hw.logicalcpu)"

WHISPER_CLI_PATH="${BUILD_DIR}/bin/whisper-cli"
VAD_MODEL_PATH="${MODELS_STAGING_DIR}/ggml-${WHISPER_VAD_MODEL}.bin"

for required_file in "${WHISPER_CLI_PATH}" "${VAD_MODEL_PATH}"; do
  if [[ ! -f "${required_file}" ]]; then
    echo "Expected file was not created: ${required_file}" >&2
    exit 1
  fi
done

rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}/bin" "${OUTPUT_DIR}/models"

cp "${WHISPER_CLI_PATH}" "${OUTPUT_DIR}/bin/whisper-cli"
cp "${VAD_MODEL_PATH}" "${OUTPUT_DIR}/models/ggml-${WHISPER_VAD_MODEL}.bin"
chmod +x "${OUTPUT_DIR}/bin/whisper-cli"

cat > "${OUTPUT_DIR}/README.txt" <<EOF
Whisper.cpp runtime assets for VS Code Whisper Lite.

Generated by:
  scripts/setup-whisper-cpp-macos-arm64.sh

Contents:
  bin/whisper-cli
  models/ggml-${WHISPER_VAD_MODEL}.bin

The large Whisper transcription model is intentionally not bundled here.
VS Code Whisper Lite downloads it from the configured GitHub release asset
into VS Code extension global storage.

Example invocation:
  bin/whisper-cli \\
    --model /path/to/downloaded/ggml-medium.en.bin \\
    --vad \\
    --vad-model models/ggml-${WHISPER_VAD_MODEL}.bin \\
    --file /absolute/path/to/audio.wav \\
    --output-json-full \\
    --output-file /tmp/whisper-output \\
    --no-timestamps
EOF

echo "Whisper.cpp runtime is ready:"
echo "  ${OUTPUT_DIR}"
